<?php
// Copyright 1999-2016. Parallels IP Holdings GmbH.
?>
<?php echo $this->renderTabs($this->tabs); ?>

    <h3><?php echo pm_Locale::lmsg('activeListHeader'); ?></h3>
<?php echo $this->activeList([
    'columnsNumber' => 1,
    'locale' => [
        'noObjects' => 'No items',
    ],
    'data' => [
        [
            'id' => 'container-1',
            'icon' =>  pm_Context::getBaseUrl() . 'images/databases.png',
            'title' =>  pm_Locale::lmsg('service1Title'),
            'status' => [
                'title' => pm_Locale::lmsg($this->itemStatus == 'started' ? 'status1Title' : 'status2Title'),
                'class' => $this->itemStatus == 'started' ? 'label-success' : 'label-inactive',

            ],
            'primaryActions' => [
                [
                    'title' => 'primary action1',
                    'link' => pm_Context::getActionUrl('index', 'list') . '/id/list',
                ],
            ],
            'summary' => [
                [
                    'name' => pm_Locale::lmsg('param1Title'),
                    'value' => 'Value 1',
                ],
                [
                    'name' => pm_Locale::lmsg('param2Title'),
                    'value' => 'Value 2',
                ],
            ],
            'toolbar' => [
                [
                    'title' => pm_Locale::lmsg($this->itemStatus == 'started' ? 'action2Title' : 'action1Title'),
                    'iconClass' => $this->itemStatus == 'started' ? 'icon-delete' : 'icon-start',
                    'link' => pm_Context::getActionUrl('index', 'service1') . ($this->itemStatus == 'started' ? '/stop' : '/start'),
                ],
                [
                    'title' => pm_Locale::lmsg('action3Title'),
                    'iconClass' => 'icon-restart',
                ],
                [
                    'title' => pm_Locale::lmsg('action2Title'),
                    'iconClass' => 'icon-delete',
                ]
            ],
            'services' => [
                [
                    'title' => 'NewService',
                    'icon' => pm_Context::getBaseUrl() . 'images/file-manager.png',

                    'link' => pm_Context::getActionUrl('index', 'form') . '/id/form',
                    'toolbar' => [
                        [
                            'title' => pm_Locale::lmsg('toolbarTitle'),
                            'link' => pm_Context::getActionUrl('index', 'form') . '/id/form',
                        ],
                    ],
                ],
            ],

            'additionalHtml' => '<H3>' . pm_Locale::lmsg('htmlBlock') . '<H3>',
            'actions' => [
                [
                    'title' => pm_Locale::lmsg('action5Title'),
                    'icon' => pm_Context::getBaseUrl() . 'images/panel.png',
                    'link' => pm_Context::getActionUrl('index', 'form') . '/id/form',
                ],
                [
                    'title' => pm_Locale::lmsg('action6Title'),
                    'icon' => pm_Context::getBaseUrl() . 'images/manage.png',
                    'link' => pm_Context::getActionUrl('index', 'tools') . '/id/tools',
                ],
            ]
        ],
        [
            'id' => 'container-2',
            'icon' =>  pm_Context::getBaseUrl() . 'images/details.png',
            'title' => pm_Locale::lmsg('service2Title'),
            'status' => [
                'title' => pm_Locale::lmsg('status2Title'),
                'class' => 'label-inactive',
            ],
            'summary' => [
                [
                    'name' => pm_Locale::lmsg('param3Title'),
                    'value' => 'Value 3',
                ],
            ],
            'toolbar' => [
                [
                    'title' => pm_Locale::lmsg('action4Title'),
                    'iconClass' => 'icon-start',
                ],
            ],
        ],
    ],
]);
